# Generated by Django 5.1.2 on 2024-11-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tasks', '0001_initial'),
        ('files_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold', models.BooleanField(default=False)),
                ('facing', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_app.file')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tasks.shape')),
            ],
        ),
    ]
