# Generated by Django 5.1.2 on 2024-11-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tasks', '0002_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='facing',
            field=models.CharField(default='north', max_length=100),
        ),
        migrations.AddField(
            model_name='shape',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Plot',
        ),
    ]
