# Generated by Django 5.1.2 on 2024-11-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tasks', '0004_category_shape_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Up to 15 cents'), ('MEDIUM', '15-30 cents'), ('LARGE', 'Above 30 cents')], default='SMALL', max_length=10),
        ),
    ]
