# Generated by Django 5.1.2 on 2024-11-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tasks', '0005_shape_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the shape'),
        ),
        migrations.AddField(
            model_name='shape',
            name='name',
            field=models.CharField(default='Unnamed Shape', help_text='Name or identifier for the shape', max_length=100),
        ),
    ]
